name: Docker Image CI

on:
  workflow_dispatch:
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker buildx build ./Source --file ./Docker/build.dockerfile --tag ${{ secrets.DOCKER_REGISTRY  }}/${{ secrets.IMAGE_NAME }}:${{ github.run_number }}
      
    - name: Docker login
      run:
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Docker push
      run:
          docker push --tag ${{ secrets.DOCKER_REGISTRY  }}/${{ secrets.IMAGE_NAME }}:${{ github.run_number }}
