name: .NET

on:
  pull_request:
    branches: [ master, dev ]
    paths:
      - 'src/**'
      - 'tests/**'
jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.203
      - name: Install dependencies
        run: dotnet restore ITMO.Dev.ASAP.sln
      - name: Build
        run: dotnet build ITMO.Dev.ASAP.sln -c Release --no-restore
      - name: Test
        run: dotnet test ITMO.Dev.ASAP.sln -c Release --no-restore --no-build -l trx --results-directory ./allure-results
