name: .NET

on:
  pull_request:
    branches: [ master, dev ]
    paths:
      - 'Source/**'
jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore Source/ITMO.Dev.ASAP.sln
      - name: Build
        run: dotnet build Source/ITMO.Dev.ASAP.sln --configuration Release --no-restore
      - name: Test
        run: dotnet test Source/ITMO.Dev.ASAP.sln --no-restore --verbosity normal
