name: .NET
concurrency: dotnet-build

on:
  pull_request:
    branches: [ master, dev ]
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/dotnet-build.yml'
      
  workflow_dispatch:

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    permissions: write-all
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.203

      - name: Cache nuget packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/*.Packages.props', '**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Install dependencies
        run: dotnet restore ITMO.Dev.ASAP.sln

      - name: Build
        run: dotnet build ITMO.Dev.ASAP.sln -c Release --no-restore

      - name: Test
        run: dotnet test ITMO.Dev.ASAP.sln -c Release --no-restore --no-build -l trx --results-directory ./allure-results

      - name: Cache history
        uses: itmo-is-dev/cache-always@v3.3.1
        with:
          path: "${{ github.workspace }}/allure-history"
          key: allure-history
          restore-keys: |
            allure-history

      - name: Prune history cache
        run: |
          REPO=${{ github.repository }}
          BRANCH="refs/pull/${{ github.event.pull_request.number }}/merge"
          gh extension install actions/gh-actions-cache
          gh actions-cache delete allure-history -R $REPO -B $BRANCH --confirm
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Upload GitHub Pages artifact
        if: always()
        uses: actions/upload-pages-artifact@v1.0.8
        with:
          path: "${{ github.workspace }}/allure-history"

      - name: Deploy Allure reports to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2.0.1

      - name: Post allure test run link
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            Link to allure test run:  
            https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ github.run_number }}