name: Start Test

on:
  push:
    branches: [ dev ]
    paths:
      - 'src/**'
      - 'Docker/build.dockerfile'

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Test
    runs-on: [ self-hosted, shreks-vm ]
    
    steps:
      - name: Docker Prune
        run: echo "Pruning docker builder cache" && docker builder prune -f

      - uses: actions/checkout@v2

      - name: Run deploy script
        run: YaCloud/start_test.py