name: Start Prod

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'Docker/build.dockerfile'

  workflow_dispatch:
    
jobs:
  deploy:
    name: Deploy Prod
    runs-on: [ self-hosted, shreks-vm ]
    
    steps:
      - name: Docker Prune
        run: echo "Pruning docker builder cache" && docker builder prune -f

      - uses: actions/checkout@v2

      - name: Run deploy script
        run: ./deployment/run_prod.sh